[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3-pip ffmpeg",
    "pip3 --version"
]

[phases.install]
cmds = [
    "pip3 install -r requirements.txt"
]

[start]
cmd = "python3 main.py"
