[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg python3-pip python3-venv"
]

[phases.install]
cmds = [
    "python3 -m pip install --user -r requirements.txt"
]

[start]
cmd = "python3 main.py"

[environment]
PATH = "/root/.local/bin:$PATH"
